// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKJCl_d43CkR-GPdgZuOpqj2jYR9ISwM',
    appId: '1:394335345045:web:9bea491c390c5dc0037e9c',
    messagingSenderId: '394335345045',
    projectId: 'satipasala-org',
    authDomain: 'satipasala-org.firebaseapp.com',
    databaseURL: 'https://satipasala-org.firebaseio.com',
    storageBucket: 'satipasala-org.appspot.com',
    measurementId: 'G-06M3TC7W10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9IUs2Hwg_7hUYAa3IUJSuvO7bI7ANeA',
    appId: '1:394335345045:android:5f272efa78b92bd7037e9c',
    messagingSenderId: '394335345045',
    projectId: 'satipasala-org',
    databaseURL: 'https://satipasala-org.firebaseio.com',
    storageBucket: 'satipasala-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfBAfYqc4GeCjFq-nXqFlVgfV6pz0ZK8',
    appId: '1:394335345045:ios:6068ca4926ce292e037e9c',
    messagingSenderId: '394335345045',
    projectId: 'satipasala-org',
    databaseURL: 'https://satipasala-org.firebaseio.com',
    storageBucket: 'satipasala-org.appspot.com',
    androidClientId: '394335345045-umcukaqi84j007tntsou8qpighqeq23t.apps.googleusercontent.com',
    iosClientId: '394335345045-c9rq4t9oc5r12u24m59dmstoimrbir15.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfBAfYqc4GeCjFq-nXqFlVgfV6pz0ZK8',
    appId: '1:394335345045:ios:5e0f0c769d542624037e9c',
    messagingSenderId: '394335345045',
    projectId: 'satipasala-org',
    databaseURL: 'https://satipasala-org.firebaseio.com',
    storageBucket: 'satipasala-org.appspot.com',
    androidClientId: '394335345045-umcukaqi84j007tntsou8qpighqeq23t.apps.googleusercontent.com',
    iosClientId: '394335345045-qgdk3rgcsa09srpuav4knmcv1ucb15tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
