// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJU-Vt8BC_GbTkK4DSEiNux36AkslgiM',
    appId: '1:1004489113608:web:937d7a8e43b90aebe311bd',
    messagingSenderId: '1004489113608',
    projectId: 'satipsala-dev',
    authDomain: 'satipsala-dev.firebaseapp.com',
    storageBucket: 'satipsala-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0fNg_Ctt9AH_uYncCYyBonc_gt-aJGc',
    appId: '1:1004489113608:android:84ae3d65a2a0d268e311bd',
    messagingSenderId: '1004489113608',
    projectId: 'satipsala-dev',
    storageBucket: 'satipsala-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDks_xTdii8mk4uTE3b60KP52RlCyLcXWI',
    appId: '1:1004489113608:ios:3dd6f27b40e562e4e311bd',
    messagingSenderId: '1004489113608',
    projectId: 'satipsala-dev',
    storageBucket: 'satipsala-dev.appspot.com',
    iosClientId: '1004489113608-tpohk9ge9ctnqdi0hl3cm4dj0q0tcf7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDks_xTdii8mk4uTE3b60KP52RlCyLcXWI',
    appId: '1:1004489113608:ios:9299784dde8275fde311bd',
    messagingSenderId: '1004489113608',
    projectId: 'satipsala-dev',
    storageBucket: 'satipsala-dev.appspot.com',
    iosClientId: '1004489113608-bv1nluv1anioos7ig4nrd226tgcngpec.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
